Improve fail message when library doesn't exist
When /foo doesn't exist in the fmf root tmt should provide better error
than saying `AttributeError: 'NoneType' object has no attribute 'data'`